### ISSUE TITLE
The API key error

### ISSUE THREAD

**Issue by amir5485** [Mrvishal2k2/TG-RenameBot#31]
Traceback (most recent call last):
  File "bot.py", line 51, in <module>
    Bot().run()
  File "/root/TG-RenameBot/venv/lib/python3.8/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bot.py", line 44, in start
    await super().start()
  File "/root/TG-RenameBot/venv/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/root/TG-RenameBot/venv/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
    await self.load_session()
  File "/root/TG-RenameBot/venv/lib/python3.8/site-packages/pyrogram/client.py", line 574, in load_session
    raise AttributeError("The API key is required for new authorizations. "
AttributeError: The API key is required for new authorizations. More info: https://docs.pyrogram.org/start/auth

**Comment by Mrvishal2k2** [comment]
Amir, i appreciate you on your first issue on github.

The error clearly says that it's issue with authorisation.

So please recheck your APP_ID, API_HASH, TG_BOT_TOKEN .
Any wrong value with this could have been a source of the issue you got.

So please fill the required variables correctly and try again.
If you aren't able to fix yourself, please get in touch with me on telegram, so we can help you there. (Links are mentioned in the repo readme)
Username on telegram : Mrvishal_2k2
